Add delegated identity API support to spire-api package
maxlambrecht/rust-spiffe pull request #43
Opened 2023-08-14 15:57 UTC by EItanya

2023-08-14 21:37 UTC, maxlambrecht requested changes
Thanks for this work, @EItanya!

2023-08-14 21:37 UTC, maxlambrecht commented on .github/workflows/ci.yml
> +      SPIFFE_ADMIN_ENDPOINT_SOCKET: unix:/tmp/spire-agent/admin/api.sock
I suggest renaming the variable to `SPIRE_ADMIN_ENDPOINT_SOCKET`, as it aligns more with the specific functionality within SPIRE rather than the broader SPIFFE specification. Unlike the other variable, this one is not defined in the SPIFFE spec.

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/Cargo.toml
> +spiffe = { path = "../spiffe" }
Considering that the crates in this repository will be versioned independently, it would be prudent to pin the `spiffe` dependency to a specific version when publishing the `spire-api` crate. This ensures that anyone using a published version of the `spire-api` crate will receive a consistent and known-good version of the `spiffe` crate. By explicitly specifying the version, we maintain control over the compatibility of the dependencies.

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/Cargo.toml
> +thiserror = "1.0"
I noticed several new dependencies being introduced in this pull request:

```
thiserror = "1.0"
url = "2.2"
asn1 = { package = "simple_asn1", version = "0.6" }
x509-parser = "0.15"
pkcs8 = "0.10"
jsonwebtoken = "8.3"
jsonwebkey = { version = "0.3", features = ["jsonwebtoken", "jwt-convert"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zeroize = { version = "1.6", features = ["zeroize_derive"] }
time = "0.3"
```

What part of the code requires each of these dependencies?

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/agent/delegated_identity.rs
> +/// Gets the endpoint socket endpoint path from the environment variable `SPIFFE_ENDPOINT_SOCKET`,
```suggestion
/// Gets the endpoint socket endpoint path from the environment variable `ADMIN_SOCKET_ENV`,
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/agent/delegated_identity.rs
> +    pub async fn stream_x509_svids(
I like this name for the streaming method. 👌

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/agent/delegated_identity.rs
> +}
Would it make sense to also include the JWT-related methods as they are part of the SPIRE Delegated Identity API?

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/agent/delegated_identity.rs
> +use spiffe::workload_api::client::{ClientError, DEFAULT_SVID};
This import is ok for now, it'll be changed when the `spiffe` create is refactored in multiple features.

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/agent/delegated_identity.rs
> +    ) -> Result<impl Stream<Item = Result<X509Svid, ClientError>>, ClientError> {
what do you think of aliasing this return type?

```
type X509SvidStreamResult<S> = Result<S, ClientError>
where
    S: Stream<Item = Result<X509Svid, ClientError>>;
```

I think it could be defined in the `spiffe` crate and reused here.

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/agent/delegated_identity.rs
> +    }
```suggestion
    fn parse_x509_svid_from_grpc_response(
        response: SubscribeToX509sviDsResponse,
    ) -> Result<X509Svid, ClientError> {
        let svid = response
            .x509_svids
            .get(DEFAULT_SVID)
            .ok_or(ClientError::EmptyResponse)?;

        let x509_svid = svid.x509_svid.as_ref().ok_or(ClientError::EmptyResponse)?;

        let total_length = x509_svid.cert_chain.iter().map(|c| c.len()).sum();
        let mut cert_chain_bytes = Vec::with_capacity(total_length);

        for c in &x509_svid.cert_chain {
            cert_chain_bytes.extend_from_slice(c);
        }

        X509Svid::parse_from_der(&cert_chain_bytes, svid.x509_svid_key.as_ref())
            .map_err(|e| e.into())
    }
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/agent/mod.rs
> +
```suggestion
//! Agent API
//!
//! Consists of the following APIs:
//! - `delegated_identity`: For managing delegated identities.
//! - `debug`: (Not yet implemented).
//!
//! # Note
//! Access these APIs via the `admin_socket_path` in the [agent configuration file](https://spiffe.io/docs/latest/deploying/spire_agent/#agent-configuration-file).
//!
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +//!
```suggestion
//! Selectors conforming to SPIRE standards.
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +/// User-facing version of underlying proto selector type
```suggestion
/// Converts user-defined selectors into SPIFFE selectors.
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +/// Selector represents a SPIFFE ID selector.
```suggestion
/// Represents various types of SPIFFE identity selectors.
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +    Generic((String, String)),
```suggestion
    /// Represents a SPIFFE identity selector based on Kubernetes constructs.
    K8s(K8s),
    /// Represents a SPIFFE identity selector based on Unix system constructs such as PID, GID, and UID.
    Unix(Unix),
    /// Represents a generic SPIFFE identity selector defined by a key-value pair.
    Generic((String, String)),
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +
```suggestion

/// Converts Kubernetes selectors to their string representation.
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +}
```suggestion
/// Represents SPIFFE identity selectors based on Unix process-related attributes.
#[derive(Debug, Clone)]
pub enum Unix {
    /// Specifies a selector for a Unix process ID (PID).
    Pid(u16),
    /// Specifies a selector for a Unix group ID (GID).
    Gid(u16),
    /// Specifies a selector for a Unix user ID (UID).
    Uid(u16),
}
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +
```suggestion

/// Converts a Unix selector into a formatted string representation.
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/src/selectors.rs
> +}
```suggestion
/// Represents a SPIFFE identity selector for Kubernetes.
pub enum K8s {
    /// SPIFFE identity selector for a Kubernetes service account.
    ServiceAccount(String),
    /// SPIFFE identity selector for a Kubernetes namespace.
    Namespace(String),
}
```

2023-08-14 21:37 UTC, maxlambrecht commented on spire-api/tests/delegated_identity_api_client_test.rs
>      }
There should be tests exercising the streaming methods.

2023-08-14 21:51 UTC, EItanya commented on spire-api/Cargo.toml
> +thiserror = "1.0"
Good point, these were copy-pasta, I will remove

2023-08-14 21:53 UTC, EItanya commented on spire-api/src/agent/delegated_identity.rs
> +}
Yes, I didn't need them immediately so I skipped, but happy to add them as well!

2023-08-14 21:58 UTC, EItanya commented on spire-api/src/agent/delegated_identity.rs
> +    ) -> Result<impl Stream<Item = Result<X509Svid, ClientError>>, ClientError> {
100%, this one is a mouthful

2023-08-15 01:41 UTC, EItanya commented on spire-api/src/agent/delegated_identity.rs
> +    ) -> Result<impl Stream<Item = Result<X509Svid, ClientError>>, ClientError> {
Turns out this isn't supported? https://github.com/rust-lang/rust/issues/89122

2023-08-15 20:03 UTC, maxlambrecht commented on spire-api/src/agent/delegated_identity.rs
> +    ) -> Result<impl Stream<Item = Result<X509Svid, ClientError>>, ClientError> {
I see, that's still experimental.

2023-08-15 20:05 UTC, merged